language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - make cov
after_success: coveralls