@startuml(id=style)
!theme crt-amber
!pragma teoz true
skinparam componentStyle rectangle
skinparam backgroundColor transparent
skinparam backgroundColor #3C3D3E

<style>
fontColor: #fda501
note, group {
  backgroundColor: #151515
}
note {
  fontStyle: bold
}
box {
  lineStyle: 0
  roundCorner: 8
  linecolor: #151515
}
</style>

header "FamiLAB Access Controller"
hide footbox
@enduml

@startuml
!include _shared.puml!style
component TestComponent
@enduml
