@startuml

title FamiLAB Access Control Phase 1
hide footbox

participant user as "User"

box "Access Control Point"
    participant reader as "Card Reader" <<MFRC522 >>
    participant lock as "Door Lock" <<Solenoid>>
    participant mc as "Microcontroller" <<ESP-32>>
end box

box "Raspberry Pi"
    participant server as "Server"
end box

box "Cloud"
    participant google as "Google Sheet"
end box


== Initialization ==

mc -> reader: "Hey, lemme know when\nthere's a thing"

== Badge Entry: Valid ==

user -> reader: User scans badge
    activate user
    activate reader
    reader -> mc: Alert badge number
        deactivate reader
        activate mc
        mc -> server: Validate badge number
            activate server
            server -> google: Fetch all users and badges
                activate google
                return All users and badges
            server->server: Compare badge number\nto users list
            return Badge number valid
        lock <- mc: Unlock
        deactivate mc
    user <- lock: User can enter
    deactivate user

== Badge Entry: Invalid ==

user -> reader: User scans badge
    activate user
    activate reader
    reader -> mc: Alert badge number
        deactivate reader
        activate mc
        mc -> server: Validate badge number
            activate server
            server -> google: Fetch all users and badges
                activate google
                return All users and badges
            server->server: Compare badge number\nto users list
            return Badge number invalid
        user <- mc: Beep? Flash red light?

@enduml
